# Generated by Django 5.2.7 on 2025-10-29 07:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('doc_type', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport')], default='National ID', max_length=20)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(default=datetime.date(2035, 10, 27))),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
