# Generated by Django 5.2.7 on 2025-10-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_servicerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentagency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServiceTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
