# Generated by Django 5.2.7 on 2025-10-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_governmentagency_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='display_name',
            field=models.CharField(default='Primary Account', max_length=100),
        ),
    ]
