# Generated by Django 5.2.7 on 2025-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='previous_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
