# Generated by Django 5.2.7 on 2025-11-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_bankaccount_previous_iban_delete_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='previous_iban',
        ),
    ]
