# Generated by Django 5.2.7 on 2025-11-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_trafficfine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
