# Generated by Django 5.2.7 on 2025-11-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='credit_card_number',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='expiration_date',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='security_code',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
