# Generated by Django 5.2.7 on 2025-11-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_bankaccount_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='security_code',
            field=models.IntegerField(),
        ),
    ]
